dist: trusty
language: R
services:
- docker
cache:
- packages
env:
  global:
  - DOCKERHUB_ORGANISATION=komparo
  - DOCKERHUB_REPO=tde_method_random
  - secure: Bk2iPgEavAxy0xvNl6CtFfSHyp9sDF7j9lIHNdS4KKXr5G7vgq2klVqLTJ9rh8bXw+q+vzxrIHvwkL3igqgRaGIUI8l6dq2KKgAo6gUup7c43U1zF8Pi+nyA+S8eX2gZQttNJABYYlp5gro70Sg31Zt30LSMtK1OAH4gWC/s1im9xMRnuVQTKuoORFBINnohBbqbxu9Yb4KKtIiNa6T8qhVxHu0mn+5E6JX+Wi7ICeIo8hPJ+33Z+j+yXKdBPnznjjzZR0qigjWwjtWVfuqq6X8ADCMrwC7jgUdh1Y3wRL1V871cIjiJ+Px0IfAZBBw6D1rUDbgI88+HYR9pVMcWZOf6MZUDrUHz0+YfqYd9mB8jh1L/0l2JHgfsSigUpnC2ssww15y8DadtTSoQa6gDeFP6kJKijmVnxJwaefyUMO5OArWsIlcT51l+VlB3HTXOsdqLZolEWHF5LH6HXOePOdcydyuiC+b2DJ37rQwa9F/GYG3+TWzJjBQoyKQQPOMvE0l2jMLSKx1weHvbZkqcWsagl/pRKw0CudSmj5y30No7x6VDXFwfhvYN+4pA5kv7QAMAhvd0DU9JzyhxY/MgU6C4fu6q/MCTKvVv8d1oHOb0HMR93y3/kvJN78qhRzyu3K+GkOPXbKiGdiZHjucODiSVYKwQycdh3UlDGkyHmwY=
  - secure: h3K/WACg5FT2GRAj1BufMM7mZl5mFw6nIQ3pyKmS8jVmCHBeR8CgUElo5bmfvIX5cEe+uLX1aELaFjzit9NIBRbssowqEtoOID4K6gRhJB7vq7j5OkibRFhKkMIouPJTfwbyjZUu2v3qZPdCjyqdxq4MRYiX5U9+5rovBF+vU9m1HPZ9YZ5wUGtqN7Xx/qZ1Hm7+HhlapaPjbyM7sd+zuYg4uef89DiK5Uf8HYs0NJyGX4lY7tYyzmbDhnjphUTa4xGEmP7gF2GqqegoZGForwZXb/sBiIc9eBXFo9Q5IzigbPIccAp09PYTCo+m+4jmD57chbovvBDDcZICaPZ8HIxSyiWzEbMjrrzCxqOpQMkl4kBg+0Xv/J5vJMVOvk4Rh7XuLwUMlhEfsvMIxD2Bh8ikoiAHUt4vYYHUGalFO++ok996ssdcKGGxbQQcSWpo19dM5unQr4Bp4MzwR7xX0qQ6pXwTI3FBK/44twsTkrkg5EUwrc8Pzsn7DgyAjbm9aPLOJj3QM1Hq73PhrUrGnhbA6LypHpnUvJQGWtWHV6k+54yZKZ0W3YtoC3Io1IIQsvdEZwfcuaqFiYXI1uer8epP3nImG3qgQkr5Iw+k2FMtzAURX87yBqKuELPoFNd4lCjve6zKbSPDg/wvxiNWGgmqKNINhzl7SgWXhiPDxKc=
  - secure: rYvQPsoUNzQ30MDAfdN+Kn75kWQf8CEfRS5TgO2WvAkUW9Oz9ll7HObyfv3+X8A9o0C7m24l6QUNkkozwcBVM8Tou3LPrCbiRnzTvL5pVhhZfv5SUPh71mYTANhH4S8aZsEndc9TbHyf81sXveCUQyZdXEdD4BkcvP0WgoHyxDv5QHPg5GLMaKuDrEGds05CxODmOPch96BWCPbBuvrHH41pMKv86VfSaizoUQD4Nw5lVzMPsToKRmOjgBjygncNo9ktDgXGZ8ju9ZMjPwhSJSw6iIhFdGkkIJhlQNsNhjcU8zI0NI3m2A6RCoDvgj2xT7DCtRBTqUo3bKk4o4cZDmGwIG23hPvivVWKHhzZ/kMWjHXonLOPwFaFjwo/Zsg15Ea4c1igsNEnvBOloJiMXoiUyu/6hlR3WU2TmCc/OdQGkDoHOuXbjtD5LbZZuXuHjZtp6rcLzOyYFGeWvQFnK3Hwk3YGNiVfKqxNA16Kc8JNJGSSqxJRxckxTEFfWk7BWAH7JhFqvR6RPSOrM/fsqOZud0DqjBfsAsQA3UO/Dg402DMDx721mH/eKNg2ZBVtzeWNBphOGuRMlnbey5gLajrIhUE8SCj55WAYdjx8+ppiLRor9FlqmoHjF0GXqKfsm8mH4Qm1HlTxKxIgpJLrC5qXBZ+YJalaE055BmuL+Gk=
before_install:
- git clone https://github.com/komparo/travis_scripts.git
- echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
- docker pull ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO} || true
install:
- R -e "install.packages('devtools')"
- R -e "devtools::install_github('komparo/tde/package@devel')"
after_install:
- docker images
script:
- Rscript test.R
deploy:
  provider: script
  script:
  - docker push ${DOCKERHUB_ORGANISATION}/${DOCKERHUB_REPO}
  on:
    branch: master
  skip_cleanup: true
